### ISSUE TITLE
use mvn clean

### ISSUE THREAD

**Issue by luster** [chenwill98/ECE-366-Agora#5]
https://github.com/chenwill98/ECE-366-Agora/blob/master/Backend/apolloBackend/test_script

`mvn clean` will remove the `target` dir.

So you can just run `mvn clean package` on the command line. Your test script might include backend and frontend tests together (though not required)

```bash
mvn clean package && yarn test
```

**Comment by guybaryosef** [comment]
ah that is more compact- thank you!
