### ISSUE TITLE
Codestyle comment

### ISSUE THREAD

**Issue by luster** [chenwill98/ECE-366-Agora#7]
Java typically uses `camelCase` rather than `snake_case`. Class names (including tests) should always start with an upper case letter.

The backend code is shaping up quite nicely, good job! Not a requirement to change to camelCase, but I thought it was worth mentioning that that is the style for writing Java.

**Comment by guybaryosef** [comment]
Although there are probably errors and exceptions, we generally tried to maintain a scheme where methods are in `camelCase`, fields are in `snake_case`, and classes start with an upper case letter (will fix the test class names now).

So generally variables and functions are differentiated only by whether there are parentheses following the decelerator?

**Comment by luster** [comment]
Generally everything follows camelCase in Java. What's important is picking a convention and sticking to it, so that's totally fine!
